name: Build Release

# Step 1: Choose the branch or branches you want to run this workflow
# Whenever A Code Pushed into master Branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Job Started Debug Build
    runs-on:  Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Java JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

      # Permission
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build Gradlew
      - name: Build with Gradle
        run: ./gradlew build

      # Build Release Apk
      - uses: r0adkll/sign-android-release@v1
        name: Signed Apk
        id: sign_app
        with:
          releaseDirectory: |
            app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "29.0.1"
      - uses: actions/upload-artifact@v2
        with:
          name: Signed Apk Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - uses: Tlaster/android-sign@v1
        name: Sign app APK
        with:
          releaseDirectory: |
            app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          APP_FOLDER: app
      run: ./gradlew build
